### ISSUE TITLE
problem with make build

### ISSUE THREAD

**Issue by andferrari** [SpheMakh/HI-Inator#9]
Hi!

today `make build` terminates with:

```
Reading state information...
E: Unable to locate package casacore
The command '/bin/sh -c apt-get update && apt-get install -y time wsclean git casacore python-pip' returned a non-zero code: 100
make: *** [build] Error 1
```

Am I wrong somewhere ? Thank you for your help

**Comment by sphemakh** [comment]
Hi, Sorry again. Some debian packages have been moved around but the docker images haven't been updated. I'm working on docker images especially for these simulations which I'll maintain myself, to avoid this type of situation in future. 

This should be fixed in a day or two. Sorry for the inconvenience.

**Comment by sphemakh** [comment]
@andferrari The bug has been fixed. Some minor changes you should note:
1. First completely replace the pipeline

```
rm HI-Inator -rf && git clone https://github.com/sphemakh/HI-Inator.git
```
1. Two, the download option has been removed, the data that was downloaded is now part of the container.
2. `make build` and  `make run config=<config file>` should do the trick from now on

everything else should be the same as before.

**Comment by andferrari** [comment]
Great ! 
Everything runs smoothly now.
